# SwiftLint Configuration for Prism Player
# 严格模式配置，符合移动端开发最佳实践

# 排除路径
excluded:
  - .build
  - "**/.build"
  - DerivedData
  - "*.xcodeproj"
  - "*.xcworkspace"
  - Tests/Fixtures
  - Tests/Mocks
  - apps/*/Resources/*.xcassets
  - .swiftpm
  - "**/.swiftpm"
  - Pods
  - Carthage

# 包含的路径
included:
  - apps
  - packages

# 启用的可选规则
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 禁用的规则
disabled_rules:
  - todo # 允许 TODO 注释
  - type_name # 允许更灵活的类型命名

# 规则配置
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 40
  error: 60

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z
  allowed_symbols: ["_"]

# 强制使用国际化字符串
nslocalizedstring_key:
  severity: error

# 强制解包警告（已在 opt_in_rules 中）
# force_unwrapping 已启用

force_cast:
  severity: error

force_try:
  severity: warning

# 尾随空格
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false
  severity: warning

# 空行
vertical_whitespace:
  max_empty_lines: 2

# 文件头注释（可选，根据团队规范调整）
# file_header:
#   required_pattern: |
#                     \/\/ Copyright © \d{4} Prism Player\. All rights reserved\.

# 报告配置
reporter: "xcode"
# 严格模式：将所有警告视为错误（用于 CI）
# 本地开发可注释此行
# strict: true
